Product reviews
apeschar/prestashop-webwinkelkeur pull request #3
Opened 2023-03-29 10:18 UTC by to6ko12

[sc-24913]

2023-03-29 12:29 UTC, TsankoBg requested changes

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +use Matrix\Exception;
What is this Exception class?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +        $sync_url = _PS_BASE_URL_ . __PS_BASE_URI__ . sprintf('module/%s/sync', $this->getName());
Don't hardcode the URL, check documentation https://devdocs.prestashop-project.org/8/modules/concepts/controllers/front-controllers/#accessing-a-module-front-controller

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +    private function sendSyncUrl(string $sync_url, int $shop_id): void {
No need to create local variables `$sync_url` and `$shop_id` and then pass them to `sendSyncUrl`.
Both fields can be retrieved.

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +        if (empty(Configuration::get(strtoupper($this->getName()) . '_SYNC_PROD_REVIEWS'))) {
Why don't you use `getConfigName`?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +            'api_key' => Configuration::get(strtoupper($this->getName()) . '_API_KEY'),
Why don't you use `getConfigName`?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +        if (empty(Configuration::get(strtoupper($this->getName()) . '_SYNC_PROD_REVIEWS'))) {
No need for `empty`, it can be just `!`
`Configuration::get` returns either the value or `NULL`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +
Wasn't there also mpn and brand in Prestashop?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +            $line['external_id'] = $line['product_id'];
There is no `external_id` in the API 
https://docs.webwinkelkeur.nl/api/invitations/add/#example-code

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +    private function getParsedOrderLines($order_lines) {
I would suggest renaming this to `getProducts`
```suggestion
    private function getProducts($order_lines) {
```

2023-03-29 12:29 UTC, TsankoBg commented on common/src/Module.php
> +            }
This is duplicated. Also you already do this check inside `sendSyncUrl`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +class sync extends ModuleFrontController {
This probably can be capitalized?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +        if (!Configuration::get(strtoupper($this->module->name) . '_SYNC_PROD_REVIEWS')) {
Why don't you use `getConfigName`?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +        $this->isAuthorized($request_data['webshop_id'], $request_data['api_key']);
I would move this check a bit higher, after `hasCredentialFields` and `credentialsEmpty`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +            throw new HttpException(404, 'Missing required content for product review');
`404` is a `not found` error message which is not appropriate in this case.
I would suggest removing this check. Our system does not allow product reviews with empty content.

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +            ->setCustomerId(0)
What happens when you create a pr with an empty CustomerId?
I think you should retrieve the customer with the product review email, and use this customer ID here. In case customer is not found, then use `0`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +            ->setDeleted($product_review['deleted'] ? 1 : 0)
Probably no need for `? 1 : 0`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +        $date_add = DateTime::createFromFormat('Y-m-d H:i:s', date('Y-m-d H:i:s'));
Doesn't this always return the current datetime?

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +            $this->ajaxRender('There has been an error syncing the review in PrestaShop');
Here you should return an error, instead of just some text. 
It is a communication between 2 API endpoints, not 2 people.

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +        if (!$review_id) {
What happens when the review gets deleted, does the review still exists? In magento2 I beleive we return `review_id => null`

2023-03-29 12:29 UTC, TsankoBg commented on common/src/sync.php
> +        if ($webshop_id == $curr_webshop_id && hash_equals($api_key, $curr_api_key)) {
Why don't you use `getConfigName`?

2023-03-29 12:29 UTC, TsankoBg commented on common/templates/config_form.php
> +}
Better use `!Module::isInstalled('productcomments')` , `!Module::isEnabled('productcomments')`  directly inside the ifs

2023-03-29 14:40 UTC, to6ko12 commented on common/src/Module.php
> +
MPN is added, but there is no column for brand in the products table. Should I add it?

2023-03-29 14:59 UTC, TsankoBg commented on common/src/Module.php
> +
👍  yes

2023-04-03 12:17 UTC, to6ko12 commented on common/src/sync.php
> +        if (!$review_id) {
The review still exists in Prestashop, so here it returns the review ID.

2023-04-04 12:10 UTC, TsankoBg requested changes
There are a lot of functions without type hints.

2023-04-04 12:10 UTC, TsankoBg commented on common/src/Sync.php
> +            : \PrestaShopLogger::addLog(sprintf('Saved product review with ID (%d)', $review_id));
No need to repeat this twice if the only difference is Saved/Deleted

```suggestion
\PrestaShopLogger::addLog(sprintf('%s product review with ID (%d)', $deleted ? 'Deleted' : 'Saved', $review_id));
```

2023-04-04 12:10 UTC, TsankoBg commented on common/templates/config_form.php
> +function isReviewModuleInstalled(): string {
I think this is not used anymore?

2023-04-04 12:10 UTC, TsankoBg commented on common/src/Sync.php
> +            }
This is basically the same as 
```PHP
$product_comment->setDeleted($product_review['deleted']);
$this->logReviewSync($product_review['id'], $product_review['deleted']);
```

no need for the conditions

2023-04-04 12:10 UTC, TsankoBg commented on common/src/Sync.php
> +            die();
In case the existing review has been changed, e.g. changed text/rating/title, the review will not be updated.

2023-04-05 09:24 UTC, TsankoBg requested changes

2023-04-05 09:24 UTC, TsankoBg commented on common/src/Sync.php
> +        \PrestaShopLogger::addLog(sprintf('%s product review with ID (%d)', $deleted, $review_id));
```suggestion
        \PrestaShopLogger::addLog(sprintf('%s product review with ID (%d)', $deleted ? 'Deleted' : 'Saved', $review_id));
```

2023-04-05 09:24 UTC, TsankoBg commented on common/src/Sync.php
> +        return $customer->id;
This should be tested, probably does not return int when not found

2023-04-05 09:35 UTC, TsankoBg approved these changes, later dismissed

2023-04-05 11:52 UTC, TsankoBg approved these changes

2023-04-05 11:52 UTC, merged